### ISSUE TITLE
v1.3.23 Release To Do List

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#318]
# Changes to be in v1.3.23 #

- [x] done
- [ ] not done

## New Features ## 
- [x] **Damage Falloff** (dmg for projectiles reduced beyond max range until they do 0 dmg).  Take the formula `y=5*((r)^x)`, where r is the rate of decay (and x is the weapons range value).  Allow the weapon to set the rate of r, but default it to 0.25.  Note that for normal behavior r should be equal to or less than 1 (exceeding 1 results in dmg increasing over distances exponentially which is probably not desired 99% of the time).  We'll want to have some sanity checks on the formulas to avoid overflow errors as its easy to end up with stupidly high values from a bad cfg.  I'd say it shouldn't increase damage to a value > 999, and once the dmg is less than 1, just cut off to 0.  It should only kick in if a cvar (jkg_damageFalloff) is enabled and r !=1.  
eg:
![sample falloff graph](https://i.imgur.com/s0YrYSy.png)
- [x] **Toggleable Crouching.**
- [x] New overheating mechanics: reloading only clears 50% of heat, no switching to a new weapon while overheated, switching while weapon has 50+% takes longer the hotter the weapon is (to give it time to cool off), switching while beyond the weapon's recommended heat capacity results takes even longer.
- [x] Implemented standard-sting and made other slow/speed effects possible from buffs.
- [x] Lua can now use buffs. 
- [x] Implemented first iteration of standard-emp which will help control jetpack users, and nerf electronic equipment while active.
- [x] Improved and added additional features to Lua Administrative cmds
- [x] Added back in Lua emote system
- [x] Weapon swap time is no longer hard coded.  Grenades, melee, and pistols have 25% reduced swap times from other weapons. 
- [x] #342
- [x] **Death Message Improvements.**  Tell players if they die from a headshot.  Also provide info to killer that they got a headshot if they do.
- [x] Item descriptions for all items #334 
- [x] #324 Show server version numbers in serverlist.
- [x] Dice roller, use the /roll <sides> cmd to roll dice.
- [x] Stuns now briefly freeze leg movement, and then do knockdown (instead of total freeze).  (The old version of stun is now a new debuff known as stasis-stun).
- [x] Automatic and burst weaponry can now be fired while rolling (good luck hitting anything though!)
- [x] New overheating mechanics: steam efx
- [x] Bacta Grenades have a new model/texture/efx.  Use them to heal allies.
- [x] Bacta Grenades now use their own warning noise. 
- [x] Bacta Grenades now heal a greater % of their hp from a healing over time buff, instead of instant hp.
- [x] Noodle's [new armor stuff](https://www.dropbox.com/s/v1ecxv0dwgiyfkx/zz_JKG_noodletest.pk3?dl=1) added in.
- [x] Item Tiers: Items may now specify a tier.  Most existing items use the default tier (common).  For details see [this concept](https://jkhub.org/forums/topic/10897-conceptitem-tiers-and-durability/). 
- [x] #352
- [x] Refactor ammo items (make sure ammo cycling works on all available override ammos).
- [x] Add new items to shops.

### Map Changes ### 
- [x] #339 
- [x] #340 
- [x] jkg_coruscant_lower - add ctf flags
- [x] jkg_spaceport - add ctf flags
- [x] jkg_spaceport - add turrets to help prevent deter spawn camping 
- [x] jkg_nightfall - fixed spawns (no more spawning in enemy shop)
- [x] Mos Eisley arena - vendors will cause you to get stuck if you use them without actually looking directly at them, using them again while facing them will fix this if you are close enough to do so.
- [x] Fix occasionally floating Tusken vendor in jkg_jawa_fortress.

## Bug Fixes and Balance Changes ## 
- [x] fix #314 server crashes
- [x]  Bacta should check if client is at full health before allowing consumption / Consumables that heal you can still be used when at full health
- [x]  Bacta is now more reliant on healing over time (buff) than instant heal. 
- [x]  Fixed some broken Lua animation handlers
- [x] Player names now have drop shadow during pazaak.
- [x] Entities can now be marked with the 'busy' flag (such as when they are playing pazaak, or shopping).  eg: If you challenge a player currently in another game, you'll receive a busy response. 
- [x] Removed "Press E to pick up weapon" messages on base weapons.
- [x] Carbonite debuff now reduces damage received by 50%. 
- [x] Dodge rolls no longer working?  Fixed.
- [x] Shader's for poison efx are no longer partially visible through/behind walls.
- [x] Tripmines don't chain explode #317 
- [x] Items now have weight (this doesn't affect anything yet). 
- [x] Fix #315 jetpack orientation on burst
- [x] Bacta Grenades "warning" sound #309
- [x] EE-3 Costs more than an E-11 but is arguably worse
- [x] DC-15A alternate fire mode uses the same ammo pool, but magically a different magazine
- [x] Minor Bacta Canisters have no item description at all, this may be true for other consumables too
- [x] Rolling from a fall or jump will not remove fire debuff
- [x] T-21 Repeater overheats too fast
- [x] Repeaters buffed in regards to overheating.
- [x] Controls menu doesn't have a binding set for next/previous weapon
- [x] Shields can't be equipped to ACI by using number keys.
- [x] It was possible for standard-stun to penetrate shields in certain circumstances, this is now fixed and shields should now always protect you from stunning.  This bug would also cause the player to be frozen indefinitely.
- [x] You can no longer change equipment while stunned/frozen by movement locking debuffs (such as standard-stun).    
- [x] When purchasing a new shield when inventory is full, it will unassign the old shield from the ACI and equip the new shield without taking up an ACI slot (perhaps equipping to a "non-existant" slot 10?).  This also happens with jetpacks.
- [x] #336 related to above issue.
- [x] Unable to equip jetpacks from inventory menu.
- [x] If you purchased/equipped a new shield, while you still had current shield charge and the new shield's max capacity, was less than your current shield charge, the shield would not be fully charged unless it was at exactly 100%.
- [x] Flamethrowers bypass shields completely, they should probably just deal damage to them and only set unshielded targets on fire / In the initial concept flame damage was supposed to be completely negated by shields, but still allow shielded targets to be set on fire, this is a bit of an oxymoron. 
- [x] Bacta grenades do not let you switch weapons until after they detonate, this may be affecting more than just this type of grenade.
- [x] #337 
- [x] If you cook a grenade till it explodes, you'll not be able to switch weapons (until you fire again). This may related to the issue above.  To reproduce: Obtain three plasma grenades, then cook the 1st to 100%, try switching weapons.  You won't be able to fire until firing the 2nd grenade.
- [x] While cooking a grenade, you are no longer able to sprint. -Thanks to George for the fix and Awec for reporting.
- [x] Invalid Gametypes will crash the game
- [x] Voting for said invalid gametypes will crash the game
- [x] Can't switch back to weapons with mousewheel after switching to melee
- [x] Multiple sets of body armor/leg armor can be equipped, and might even stack stats
- [x] #239 
- [x] Armor that increases maxhp does not behave properly when unequipped (extra hp is not removed). 
- [x] When at maxhp, and swapping armor sets, if the the new set increases maxhp, your current hp should be set to the new maxhp 
- [x] Armor sometimes prevents player names from being viewed when crosshair is over them
- [x] Sometimes one team gets armor in the shop and the other doesn't. ~~Perhaps armor items should be available guaranteed, but be a little bit more expensive.~~  There are now armor vendors.
- [x] Improved armor (and other item type descriptions) 
- [x] #345
- [x] Account for passive credit gain on /pay anti-exploit
- [x] Fixed Lua exploits. 
- [x] Fixed autoassign shield/jetpack aci equip exploit 
- [x] #343
- [x] Improve sniper accuracy
- [x] Improve rifle accuracy
- [x] Aim down sights/scope accuracy needs improvement on most weapons, E-11 and DC-15A are egregious examples
- [x] New item types and more filtering (such as tools, ammo, etc)  
- [x] Small and Medium ammo types don't seem to work at all except for weapons that use them by default. Switching to large ammo will make it so that you can't switch back to small or medium if the weapon had that by default. Also, these ammo types do not seem to affect clipSize at all (e.g. ACP power packs do less damage but do not have more ammo per magazine vs ACP anti-personnel rounds in the ACP Sniper Rifle)
- [x] Fixed 'miss' and 'deathfx' in ammo being mixed up in code and calling the wrong functions.
- [x] Overheating in the middle of a burst causes you to finish the burst as soon as you are able to shoot again (running out of ammo in the middle of a burst used to do this too as soon as you finished reloading, a similar fix would probably work) #347
- [x] Alternate ammo types change third person muzzle flash efx, but not first person
- [x] Fix shield gating interaction with stun debuffs (locks client up so they can't move if they have a shield and receive the buff)
- [x] Do not allow the jetpack to be activated if standard-emp is present (cuts off jetpack immediately, but it can be turned on in spurts)
- [x] Damage plums only show up for one projectile when hit by multiple projectiles in the same frame, they now stack up the damage into the same plum
- [x] Consumables are now subject to a cooldown (default 3 seconds), before a new consumable can be used.

**Comment by DarthFutuza** [comment]
Implemented Damage Decay/Falloff Beyond Range in f2b0db1.

**Comment by xycaleth** [comment]
> * Fix shops with more appropriate selections of weapons (the chances of getting an ammo type you need and a weapon that uses it the same time is pretty low and a kinda dumb mechanic).  This involves rereleasing all maps with multiple vendor types in each base.  eg: each base should have at least 1 general shopkeep, 1 ammo vendor, 1 grenade vendor and 1 medical vendor.  On smaller maps, consider placing vendors in other places in the map to create additional points of interests if there is no room at the bases.  Remove extra ammo options from the general shop and move to ammo vendor when complete.  This can be done via entity hacking for maps we don't have .map files for anymore.

The vendors etc could probably be done using the GLua scripts. It supports creating a GLua script per map which can spawn entities anywhere on the map. I think that's how the old JKG maps spawned special NPCs like for playing Pazaak etc

**Comment by DarthFutuza** [comment]
> 
> The vendors etc could probably be done using the GLua scripts. It supports creating a GLua script per map which can spawn entities anywhere on the map. I think that's how the old JKG maps spawned special NPCs like for playing Pazaak etc
That'd be a much better fix than all that work, I'll look into doing that (unless you get to it first lol).

**Comment by xycaleth** [comment]
Here's an example:

https://github.com/JKGDevs/JediKnightGalaxies/blob/master/JKGalaxies/glua/maps/jkg_arena_tatooine_night/init.lua#L14

I think `init.lua` is loaded for the map if it exists. This then loads `npcs.lu`:

https://github.com/JKGDevs/JediKnightGalaxies/blob/master/JKGalaxies/glua/maps/jkg_arena_tatooine_night/npcs.lua

**Comment by DarthFutuza** [comment]
ef6f3ce deals with pay exploits (it could be better: eg tracking credits made from kills/objectives separately, but this is good enough for now)

**Comment by DarthFutuza** [comment]
655e065 makes it so reloads only clear 50% of the weapons heat, and you can't switch weapons while heat is > 50% - needs more work for ui/sound feedback, but mechanically works fine.

**Comment by DarthFutuza** [comment]
I changed it again in a2cbcd1 so that you can switch while heat is > 50%, but it just switches slower the hotter the weapon.

**Comment by DarthFutuza** [comment]
Haven't checked to see if this is doing anything statwise, but you can definitely equip some armor duplicates at least according to the ui:

![image](https://user-images.githubusercontent.com/4450419/103427111-e03bad00-4b7b-11eb-9a56-7cb442b988a9.png)

**Comment by DarthFutuza** [comment]
'Spectator messages get cut off- (when spectating a player when they die)' this one is a bit tricky, as whoever is spectating shares the same player state as the actual player.  I haven't figured out a way to differentiate between the two yet, but the call happens in cg_playerstate.cpp inside of the CG_TransitionPlayerState() function.

**Comment by DarthFutuza** [comment]
While I thought that sting/slow debuffs were done, I've apparently introduced a bug where all debuffs result in a slow debuff also being applied.  Needs investigation.

**Comment by Silverfang22** [comment]
Rifle accuracies were done a while back, but E-11A could use a small improvement in accuracy.
Snipers still need accuracy buffs, scoped bryar rifle (sniper) is especially terrible.

**Comment by DarthFutuza** [comment]
I'm going to remove this one from this patch:
`Dismemberment doesn't seem to work`

It does seem possible to do (to corpses for example), but also seems to have a very rare chance of occurring.  This seems like something more appropriate to fix for v1.4, so I think we'll prioritize the other things before this one this patch.

**Comment by DarthFutuza** [comment]
So steam overheating efx is in the game now, I think the efx looks mostly good, but feel free to fine tune it if you're not happy with it Silverfang.  I need to adjust the name in the efx file once its finalized (I just kept the 'testing' name for now), but that's trivial.

**Comment by DarthFutuza** [comment]
Moving: Sniper Rifles (e.g. anything in sniper category that isn't a bowcaster) lay on the ground as if they were bowcasters. Need .wpn specific angles for weapons to display in world when dropped #132 to a later release, I don't think its worth doing this patch.

**Comment by DarthFutuza** [comment]
Note to self: For fixing item shop prices and shop refresh times, check jkg_inventory.cpp 's function: void JKG_Inventory_OwnerDraw_CreditsText(itemDef_t* item) {}

**Comment by DarthFutuza** [comment]
Alright August is upon us, in the interest of getting the next patch out in a timely manner, I'm cutting some items this patch and moving them to [the next patch list](https://github.com/JKGDevs/JediKnightGalaxies/issues/349).  The rest of the items remaining I would like finished this patch, but may also need to cut some of the new model ones (such as the bacta grenades and texturing items like the IR-5).  @Silverfang22

**Comment by Silverfang22** [comment]
Release successful, moving the IR-5 from this checklist to 1.3.25
